### ISSUE TITLE
Add Query Error Number for more descriptive error messages

### ISSUE THREAD

**Issue by tcashel** [jbaldwin/libwingmysql#32]
Currently if an invalid Query is provided, the only feedback given is "ERROR".  Adding a error number or message field will allow invalid queries to be logged with more detail and more easily debugged. 

using the `mysql_errono` or `mysql_error` functions on a failed `mysql_real_query` call is probably the way to go.

(mysql_errono)[https://mariadb.com/kb/en/mysql_errno/]
(mysql_error)[https://mariadb.com/kb/en/mysql_error/]

See Query.cpp line 142 for start of main if block.

**Comment by jbaldwin** [comment]
@tcashel can this one be closed as well?

**Comment by tcashel** [comment]
This is a duplicate of issue 33 so it should be removed/closed. 

- Tripp
