### ISSUE TITLE
Add More descriptive Error messages for a bad query

### ISSUE THREAD

**Issue by tcashel** [jbaldwin/libwingmysql#33]
Currently if an invalid Query is provided, the only feedback given is "ERROR".  Adding a error number or message field will allow invalid queries to be logged with more detail and more easily debugged. 

using the `mysql_errono` or `mysql_error` functions on a failed `mysql_real_query` call is probably the way to go.

[mysql_errono](https://mariadb.com/kb/en/mysql_errno/)
[mysql_error](https://mariadb.com/kb/en/mysql_error/)

See Query.cpp line 142 for start of main if block.

**Comment by jbaldwin** [comment]
Have you tried calling `Query::Error()`?

**Comment by tcashel** [comment]
Thank you,that's exactly what I need.
